version: '2'
services:
    go_services:
        build:
          context: ./golang
        ports:
          - "8080:8080"
        tty: true
        environment:
          GOPATH: ""
        volumes:
          - ./code:/go/src
        container_name: 'go_c'

