version: '2'
services:
    go_services:
        image: golang
        ports:
          - "8080:8080"
        tty: true
        environment:
          GOPATH: ""
        volumes:
          - ./code:/go
        container_name: 'go_c'

